avaya-dux/neo-react-library

package.json

now that dependabot seems to control those issues

update `package.json`, remove "resolutions"

---

.github/workflows/run-yarn.yml

as we've got a demo for him happening soon, and it took me ten second to write this
success condition:
failure condition:
PS, why yes, I do find my own joke ***hilarious***

add an "easter egg" for Flavio

---

package.json
vite.config.ts

don't export map files, do export `d.ts` files

fix build issues

---

.vscode/extensions.json
src/components/Button/Button.tsx
src/components/Icon/Icon.tsx
src/components/Image/Image.tsx

As I'm using these components and finding issues, I've either added a Jira ticket, or just made the update if it was trivial. 
*Work done*:
- I've added several JSDoc examples in places that they were missing or lacking.
- I also removed an extension recommendation that was deprecated and replaced it with the recommended replacement.
- Finally, I made a minor TS update to the `Icon` component that makes it more obvious that `aria-label` is required. (as I wasn't sure why the warning was happening when I was using it)

touchup some issues I found

---

package.json
readmes/coding-guidelines.md

[Link to updated components in GitHub](https://github.com/avaya-dux/neo-react-library/blob/documentation-update/readmes/coding-guidelines.md)
Per our discussion in standup, updating guidelines file. Also, I'll be publishing an update soon, so updating the `package.json` version.
**EXAMPLE IMAGE(S):**

add a guideline for `Parent` w/ `Parent.Child`

---

src/components/Layout/AppLayout.stories.tsx
src/components/Layout/AppLayout.tsx
src/components/index.ts

Footer Area has been added, if provided it will render at the bottom of the screen.
The only area (prop) that is required is mainContent. Any optional areas that are not provided will not be rendered. See storybook stories in Layout category.
**IMPORTANT NOTES:**
- I'm getting unexpected errors in my basic render tests. It will take time to investigate a fix so I will add tests in Part 3.

NEO-1171 AppLayout component Part2

---

src/components/Layout/AppLayout.test.jsx

This fixes some failures I was getting for the tests. No other code was changed.

NEO-1171 Adding basic layout tests

---

.github/workflows/run-yarn.yml
cypress/support/component.ts
package.json
src/components/TextInput/TextInput.test.jsx

Because we were accidentally suppressing tests failing, there were a few broken tests. I've fixed that accidental suppression, and then also the broken unit tests. Also updated version number as the last publish was borked (my fault).

fix testing (DigitalFlavio was broken)

---

src/components/Accordion/Accordion.stories.tsx
src/components/Accordion/Accordion.test.jsx
src/components/Accordion/AccordionGroup/AccordionGroup.stories.tsx
src/components/Accordion/AccordionGroup/AccordionGroup.test.jsx

merge two accordion stories for better DX+UX

---

src/standalone-stories/Introduction.stories.mdx

Add here and in [dpv3 homepage](https://github.com/avaya-dux/design-portal/pull/89)

add link to linktree

---

package.json
src/components/Notification/Notification.tsx

This is just adding some docs an bumping the package version

add jsdocs to Notification component 

---

README.md
src/standalone-stories/Introduction.stories.mdx

updating documentation per our discussion this morning in stand-up 
skipping the template ish as this is _only_ a documentation update

improve documentation on installing/using neo-react

---

src/components/Tree/Branch/Branch.tsx
src/components/Tree/Leaf/Leaf.tsx
src/react-table-config.d.ts
yarn.lock

While doing the work to resolve vulnerabilities detected by the most recent Black Duck scan, I came across an a11y linting error due to a missing `aria-selected` attribute on the Tree Branch/Leaf Components (see screenshot below). I have added the missing attributes to resolve the issue.
**EXAMPLE IMAGE(S):**

Added aria-selected attribute to Tree Branch/Leaf Component

---

package.json

bump version to 0.7.19

---

readmes/how-to-dev.md

Removed section in `how-to-dev.md` that refers to an invalid script/script that no longer exists.

Removed invalid section from readme

---

package.json

bump to 0.7.20

---

package.json

bump version after publishing 0.8.4

update version to 0.8.5

---

package.json

bump version to 0.8.6

---

.cm/define-sensitive-code-areas.cm

as github already does that for us

remove gitstream check for approvals

---

src/components/Select/utils/useDownshift.ts

[Link to updated components in Deploy Preview](https://deploy-preview-181--neo-react-library-storybook.netlify.app/?path=/story/components-select--basic-selects)

DUX-1673 fix a regression: tabbing away from multi select removes chips

---

src/components/Select/Select.test.jsx
src/components/Select/utils/useDownshift.ts

[Link to updated components in Deploy Preview](https://deploy-preview-182--neo-react-library-storybook.netlify.app/?path=/story/components-select-optionwithcheckbox--default)
Add a test for [previous pr 181](https://github.com/avaya-dux/neo-react-library/pull/181)

DUX-1673 Test tabbing away at the end of multi selection

---

src/components/PopupManager/PopupHook.test.jsx
src/components/PopupManager/PopupHook.tsx

[Stories using PopupHook](https://deploy-preview-184--neo-react-library-storybook.netlify.app/?path=/story/components-toast--default)
PopupHook code is still using React 17 render.  This pr migrates it to React 18.

NEO-1542 update to createRoot

---

package.json

Bumping version number to 0.8.9

---

src/components/Select/Select.stories.tsx
src/components/Select/Select.test.jsx
src/components/Select/Select.tsx
src/components/Select/SelectStories.css
src/components/Select/utils/SelectTypes.tsx

[Link to new Select Story](https://deploy-preview-245--neo-react-library-storybook.netlify.app/?path=/story/components-select--inline-custom-widths)
Allow use of `className` and `style` props for Select components. Added a story to show these off and a test.

NEO-1776 // update Select component

---

src/components/Notification/Notification.tsx

Forgot to update the JSDocs for the Notification in last PR

Updated JSDocs for Notification

---

src/components/Pagination/Nodes/NavListItemButton.tsx

[Pagination Storybook](https://deploy-preview-273--neo-react-library-storybook.netlify.app/?path=/docs/components-pagination--docs)
Page no longer reloads if you click the current page on the pagination

Added an if statement so the page doesnt reload when the current page is clicked.

---

src/components/Link/Link.stories.tsx
src/components/Link/Link_shim.css

[Link Component Storybook](https://deploy-preview-276--neo-react-library-storybook.netlify.app/?path=/docs/components-link--docs)

Removed Padding on Link Component

---

package.json

Including the latest neo icons and neo css library

Update release v1.0.7

---

src/components/Table/Table.stories.tsx
src/components/Table/Table.test.jsx
src/components/Table/TableComponents/TableFilter.tsx

[Link to updated components in Deploy Preview](https://deploy-preview-305--neo-react-library-storybook.netlify.app/?path=/story/components-table--advanced-filtering-and-sorting)

fix filter flicking

---

src/components/Menu/Menu.stories.tsx

[link to new story](https://deploy-preview-322--neo-react-library-storybook.netlify.app/?path=/story/components-menu--rtl-example)

put a new story into the Menu/Dropdown storybook examples

---

package.json
yarn.lock

update neo-icons, bump version

---

package.json
src/components/Table/Table.tsx
src/components/Table/TableComponents/TableToolbar.tsx
src/components/Table/helpers/FilterContext.ts
src/components/Table/types/TableTypes.ts

Resolve hack thanks to Ruthvik's input. Thus also able to remove now unused elements from the table context.

resolve hack, bump version

---

src/components/Table/Table.tsx
src/components/Table/types/TableTypes.ts

added to cover Shrisha's use-cases

Table // add `initialStatePageSize` prop

---

src/components/Table/Table.stories.tsx
src/components/Table/Table.tsx
src/components/Table/TableComponents/TableBody.tsx
src/components/Table/TableComponents/TableHeader.tsx
src/components/Table/helpers/FilterContext.ts
src/components/Table/types/TableTypes.ts

[Link to updated components in Deploy Preview](https://deploy-preview-458--neo-react-library-storybook.netlify.app/?path=/story/components-table--custom-actions)
`@avaya-dux/dux-devs`: 
- just rename

NEO-2189 rename canDrag to draggableRows

---

package.json

Updating the React library from v.1.4.5 to v1.4.6

Update React library to 1.4.6
