src/components/LeftNavigation/TopLinkItem/TopLinkItem.stories.tsx
src/components/LeftNavigation/TopLinkItem/TopLinkItem.test.jsx
src/components/LeftNavigation/TopLinkItem/TopLinkItem.tsx

- [x ] reviewed my code changes
- [x ] added any important information to this PR (description, images, GIFs, ect.)
- [x ] done an accessibility check on my work
We now update the TopLink active state if the currentUrl matches the url for that TopLinkItem

NEO-1075: LeffNav->TopLink: Active state is now driven by currentUrl value

---

src/components/Modal/BasicModal/BasicModal.tsx
src/components/Modal/BasicModal/BasicModal_shim.css
src/components/Modal/InfoModal.tsx

When displaying an InfoModal component, it will automatically center itself both horizontally and vertically in the main body of the page.
I also added the ability to pass a className and ref props to it.
**IMPORTANT NOTES:**
- As a side effect, this PR will also center the BasicModal but further work will be needed to add the other props to it.

NEO-1077 & NEO-1076: Center InfoModal/BasicModal component when it pops up

---

src/components/Table/Table.stories.tsx
src/components/Table/Table.tsx
src/components/Table/Table_shim.css
src/components/Table/types/TableTypes.ts

- [ x] reviewed my code changes
- [ x] ensured that all tests pass
- [ x] added any important information to this PR (description, images, GIFs, ect.)
- [x ] tagged Matt if any visual changes have occurred
- [ x] done an accessibility check on my work
When showRowSeparator is true, the tables will render with a separator line as indicated by the IAM Figma design. See story for details.

NEO-1073: Adding showRowSeparator prop / feature to Table component

---

readmes/how-to-dev.md

[Link to updated readme](https://github.com/avaya-dux/neo-react-library/blob/fix-link-issue/readmes/how-to-dev.md#development-linking)
Vite works a little differently than WebPack, so I've updated the instructions to be both clearer, and added a "Vite note" with a brief explanation of how/why.

update instructions on linking neo-react to other projects 

---

src/components/Radio/Radio.tsx
src/components/Radio/RadioGroup.stories.tsx
src/components/Radio/RadioGroup.test.jsx
src/components/Radio/RadioGroup.tsx
src/components/Radio/RadioGroup_shim.css

[Link to updated components in Deploy Preview](https://deploy-preview-32--neo-react-library-storybook.netlify.app/)
Re-worked RadioGroup and Radio Components as per [NEO-1140](https://jira.forge.avaya.com/browse/NEO-1140) for improved logic, accessibility and usability, added tests for new functionality, created CSS shim file for necessary updates and to accommodate using Tooltip as a child component of RadioGroup.
The main challenge in this work was to ensure the correct props were passed from the `RadioGroup` to child `Radio` Components, even when wrapped in a Tooltip. I did find a way to do this, but any feedback towards better/more elegant solutions is of course welcome.
**EXAMPLE FUNCTIONALITY GIF:**

NEO-1140: RadioGroup & Radio rework

---

package.json

`react-stopwatch` is _only_ used for a story, so I'm not sure why it was a peer dep in the first place, but now it's _only_ a dev dep, so it shouldn't cause the person any more issues after this is merged and published

remove `react-stopwatch` from peer deps as we _only_ use it for a story

---

src/components/Tab/EventHandlers/KeyboardEventHandlers.test.jsx
src/components/Tab/EventHandlers/KeyboardEventHandlers.ts
src/components/Tab/EventHandlers/KeyboardHelper.test.jsx
src/components/Tab/EventHandlers/KeyboardHelper.ts

[To test, move to the last tab using arrow keys, then press enter](https://deploy-preview-53--neo-react-library-storybook.netlify.app/?path=/story/components-tab--uncontrolled-active-tab-story)
Press "enter" on a TabLink should open link in another browser tab.

NEO-1214 open link when enter is pressed on a TabLink

---

src/components/Modal/InfoModal.tsx

https://deploy-preview-99--neo-react-library-storybook.netlify.app/?path=/story/components-modal-info-modal--portal-info-modal-example
aria-label now defaults to whatever it is passed in as title prop.

NEO-1302: aria-label no longer hardcoded.

---

package.json
src/components/Select/InternalComponents/MultiSelect.tsx
src/components/Select/InternalComponents/MultiSelectSearchable.tsx
src/components/Select/InternalComponents/SingleSelect.tsx
src/components/Select/InternalComponents/SingleSelectSearchable.tsx
src/components/Select/Select_shim.css
yarn.lock

[Select](https://deploy-preview-113--neo-react-library-storybook.netlify.app/?path=/story/components-select--basic-selects)
fixed 3 issues mentioned in the ticket:
* Spacing issues on all multiple select versions. When there are multiple chips selected, the top padding should match the version that only has a single chip.
* On multiple select, the cursor should be positioned next to the last chip rather than on a new separate line.
* hover state should not cut off focus blue border.
I have also forced focus visible on mouse click, as I want to a consistent look between mouse and keyboard actions.  Let me know if this is ok.

NEO-1388 style changes

---

src/components/Radio/Radio.tsx
src/components/Select/Select_shim.css

There is an edge case where labels on a page could have the same `id`. I've resolved that by re-using the generated id that we are already using in the `input` id. I'm not adding any new tests because this is a side-effect of our implementation and feels unnecessary to add more tests. But I can if anyone feels strongly about it. 
I also ran `yarn all` and saw that it formatted `src/components/Select/Select_shim.css`. I did not change the file, its just been formatted.

fix a11y issue for duplicate ID's for label

---

src/components/Pagination/Pagination.test.jsx
src/components/Tooltip/Tooltip.test.jsx
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/TooltipTypes.ts

[Link to Tooltip story](https://deploy-preview-119--neo-react-library-storybook.netlify.app/?path=/story/components-tooltip--default), [Link to Pagination story](https://deploy-preview-119--neo-react-library-storybook.netlify.app/?path=/story/components-pagination--default) (tooltip is on the "Item count" and "Items per page" select)
On the update DPv3 Tooltip Page, the "left" and "right" tooltips pass over the containing border. It _should_ be simple to add a class/style to the tooltip to set a proper width to fix that visual issue. It isn't currently, thus this change. 
I've added the prop `tooltipDivProps` to allow the Tooltip so that the implementor can add/edit whatever they wish. Excluding the `role` prop, as that …

Update Tooltip component to allow additional props

---

src/components/Select/utils/useDownshift.ts

[Link to updated Select Component](https://deploy-preview-123--neo-react-library-storybook.netlify.app/?path=/story/components-select--basic-selects)
There are several a11y issues with the Select components. For this PR, I am _only_ fixing one small thing. 
**BUG**: When an item is selected, Voice Over announces the selected item as "object object has been selected".
**FIX**: I've fixed this by specifying the `itemToString` in the downshift configs. 
NOTE: there are two types of select that do not announce the selected item at all. I've added `// BUG:` to those methods.

fix Voice Over announcing "object object selected" issue

---

src/components/Select/Select.tsx
src/components/Select/utils/useDownshift.ts

Like [this PR's sibling](https://github.com/avaya-dux/neo-react-library/pull/123), there are several a11y issues with the Select components. For this PR, I am only fixing one small thing.
**BUG**: when a user using a screen reader enters a Select component, the label is read twice. This is because the label _and_ the aria-label are both being read (which is correct).
**FIX**: I'm no longer forcefully setting an aria-label. Now, I only set it if there is one that is passed.

only set aria label as aria label (double speak fix)

---

package.json

By pinning the "engine" we simplified the dev experience for running neo-react, but we did not realize it forces all projects using neo-react to also use the engine version. Thus, updating engine version to allow all node versions 16+.
Also, looks like `0.7.20` has already been used, and it makes sense to update the minor version as we've done so much work. Thus updating the package version to `0.8.0`.

resolve design portal build issue (on Netlify)

---

.github/renovate.json5

This update _should_ keep [this PR](https://github.com/avaya-dux/neo-react-library/pull/200) from happening repeatedly. Specifically:
- keeps renovate from updating `.nvmrc`
- keeps renovate from updating `package.json`s `engines.node` (if the current config doesn't work, [we can try this suggestion](https://github.com/renovatebot/renovate/discussions/13521#discussioncomment-1958929))

pin node version for renovate

---

.storybook/main.ts

[Link to Accordion "docs" page](https://deploy-preview-216--neo-react-library-storybook.netlify.app/?path=/docs/components-accordion--docs)
Storybook v7 now has a config setting for auto generating documents. When I updated to v7 I set the wrong value, this fixes that so that now _all_ stories have autodocs, as they were before the v7 update. 
Components now have a auto generated "Docs" story:

set `autodocs` back to `true`

---

src/components/AgentCard/Timer.tsx
src/components/Pagination/Pagination.cypresstest.tsx

Fixing two issues that are causing a `renovate` PR to fail:
1) A type issue in the `src/components/AgentCard/Timer.tsx` file -- confirmed Component Story still working
2) Fixed linting errors related to chaining multiple methods off a single call to `cy.` in Cypress test file

Fixed type issue w/ Timer, fixed Cypress warnings re: excessive linking of methods

---

src/components/Tab/EventHandlers/KeyboardEventHandlers.test.jsx
src/components/Tab/EventHandlers/KeyboardEventHandlers.ts
src/components/Tab/Tabs.stories.tsx

[Link to updated components in Deploy Preview](https://deploy-preview-258--neo-react-library-storybook.netlify.app/?path=/story/components-tab--scrollable-vertical-tabs)
As described in title

NEO-1482 stop parent of vertical tabs from scrolling on arrow-down and arrow-up events

---

src/components/Tab/TabTypes.tsx

as all members of an array must have a `key` prop passed for the react compiler
this was found as part of the updates to DPv3

allow user to pass a `key` for all Tab components

---

src/components/TextInput/TextInput.stories.tsx
src/components/TextInput/TextInput.tsx

[Link to updated components in Deploy Preview](https://deploy-preview-281--neo-react-library-storybook.netlify.app/?path=/story/components-text-input--different-html-output-examples)
This PR fixes an issue exposed when our TextInput component has the 'required' prop set to true and it is not properly wrapped inside a 'Form' component. The bug was not in the component itself but in the way it was used.
By wrapping each TextInput story in a Form component, the correct styles and decorators now render correctly. See screenshot that shows the red asterisk next to the label for the required field.

NEO-1910: Text input required prop not working

---

package.json

because storybook started requiring it

fix storybook docs by adding new dep

---

src/components/Select/InternalComponents/SingleSelectSearchable.tsx
src/components/Select/Select.stories.tsx

[NEO-1942](https://jira.forge.avaya.com/browse/NEO-1942) shows that placeholders are not displaying correctly. I've fixed this for the searchable Select components, as that was super easy, but am still working on the non-searchable components.

NEO-1942 // fix placeholder for searchable select component (Part 1)

---

src/components/Select/InternalComponents/MultiSelect.tsx
src/components/Select/InternalComponents/SingleSelect.tsx
src/components/Select/Select.test.jsx
src/components/Select/Select.tsx

[Link to Select Storybook](https://deploy-preview-314--neo-react-library-storybook.netlify.app/?path=/story/components-select--basic-selects)
In [part one](https://github.com/avaya-dux/neo-react-library/pull/311), I fixed the styling for searchable Select components. In this PR I disallow the use of the `placeholder` for non-searchable Select components as [the HTML spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) does not allow placeholder text for the base select element, and [the placeholder prop](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/placeholder) only exists on text inputs type elements.

NEO-1942 // disallow `placeholder` prop for non-searchable Select

---

src/components/Notification/NonEventNotification.stories.tsx
src/components/Notification/Notification.tsx
src/components/Notification/NotificationTypes.tsx

[Link to updated components in Deploy Preview](https://deploy-preview-320--neo-react-library-storybook.netlify.app/?path=/story/components-notification--info-no-timestamp)
This PR adds a new showTimestamp prop that gives the ability to show or hide the date and time info that appears at the top. Previous this this change it was ALWAYS showing it. We can now hide it by setting the prop to false.
The prop value defaults to true to keep backwards compatibility with any apps currently using this component.  Here's a screenshot of a notification with the Timestamp not showing:

NEO-2100: Notification component's new showTimestamp prop

---

src/components/LeftNav/LinkItem/LinkItem.tsx

[Link to updated components in Deploy Preview](https://deploy-preview-323--neo-react-library-storybook.netlify.app/?path=/story/components-left-navigation--category-groups)
This PR fixes an edge case where if no custom navigation handler is given for a LinkItem, it will perform a default anchor navigation. A change to the Portal side navigation exposed this bug I'm now fixing.  BTW, the same has already been made for the TopLinkItem component in a previous PR.

NEO-2103: Fixed broken navigation for default anchor behavior

---

biome.jsonc
src/components/LeftNav/LeftNav.stories.tsx

@avaya-dux/dux-devs I noticed that the linting isn't as strict as I'd like it to be (it previously allowed unused variables and imports). This update makes those not allowed. 
The first run of this should fail in our CI pipeline. If it fails appropriately, I'll make the requested update, wait for it to pass, and then merge. 
EDIT: [first run failed appropriately](https://github.com/avaya-dux/neo-react-library/actions/runs/9389319755/job/25856535907?pr=415) 💯 🥳

make biome more strict

---

src/components/Table/Table.stories.tsx
src/components/Table/Table.tsx
src/components/Table/TableComponents/TableBody.tsx
src/components/Table/types/TableTypes.ts

[Link to Table story](https://deploy-preview-456--neo-react-library-storybook.netlify.app/?path=/story/components-table--multi-select-without-helper)
This adds a prop to hide the "clear row" functionality. The prop defaults to true, this story sets it to false. Easy-peasy.

allow users to hide the "clear row" in the body

---

src/components/Table/DraggableTableRow.tsx
src/components/Table/StaticTableRow.tsx
src/components/Table/Table.stories.tsx
src/components/Table/TableComponents/TableBody.tsx
src/components/Table/Table_shim.css

[Link to updated components in Deploy Preview](https://deploy-preview-504--neo-react-library-storybook.netlify.app/?path=/story/components-table--custom-actions)
Dev only PR:
`@avaya-dux/dux-devs`: added Dark mode switch to Table -> CustomAction 
- show a table if row.name starts with Sir
- show a form if row.name starts with Madam
- show simple text for the rest

NEO-2118 update table story to showcase various inset table content

---

src/components/Icon/Icon.test.tsx
src/components/Icon/Icon.tsx
src/components/IconButton/IconButton.test.jsx

`@avaya-dux/dux-devs`: getting us to 100% code coverage

Icon // improve test, get 100% code coverage

---

src/components/IconButton/IconButton_shim.css

[Link to updated components in Deploy Preview](https://deploy-preview-591--neo-react-library-storybook.netlify.app/?path=/docs/components-iconbutton--docs)
Fixed bug in IconButton styles that caused Spinner animation to be misaligned due to extra margin
**EXAMPLE FUNCTIONALITY GIF:**
Before:
After:

Removed unintentional margin on IconButton Spinner animation
